[mypy]
follow_imports = skip

[mypy-second_brain.ai.*,second_brain.healthtrack.*]
disable_error_code =
    no-untyped-def,
    type-arg,
    no-any-return,
    no-untyped-call,
    untyped-decorator,
    var-annotated
